version: '3'

services:
  reverse-proxy:
    image: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true 
      - --providers.docker=true
    #  - --log.level=DEBUG
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /data/conf/traefik.yml:/etc/traefik/traefik.yml

# add traefik to the web network so that it can send traffic to other containers
networks:
  default:
    external:
      name: apps_docker_default # network-scoped alias is supported only for containers in user defined networks