apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    run: es
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    name: tcp
  selector:
    run: es
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      run: es
  replicas: 1
  template:
    metadata:
      labels:
        run: es
    spec:
      containers:
      - name: es
        image: fzinfz/es:i3wm
        command: ["es"]
        args: ["notebook","--ip=*","--allow-root","--port=8888"]
        ports:
        - containerPort: 8888
          protocol: TCP
