---
- name: Check OpenWrt version of routers
  hosts: routers
  gather_facts: false
  tasks:
    - name: Retrieve OpenWrt system board info
      ansible.builtin.raw: >
        ubus call system board 2>/dev/null ||
        cat /etc/openwrt_release 2>/dev/null ||
        cat /etc/os-release
      changed_when: false
      register: openwrt_version

    - name: Display version info
      ansible.builtin.debug:
        var: openwrt_version.stdout_lines

- name: Show wireless SSID
  hosts: wireless
  gather_facts: false
  tasks:
    - name: Run wireless_show_ssid.sh
      ansible.builtin.script: ../../openwrt/uci/wireless_show_ssid.sh # run.sh will convert to raw
      changed_when: false
      register: command_result

    - name: Display SSID info
      ansible.builtin.debug:
        var: command_result.stdout_lines  