- name: check nf
  hosts: routers
  gather_facts: false
  tasks:
    - name: Run nf_conntrack check script
      ansible.builtin.raw: >
        curl -sS http://192.168.88.72:8100/scripts/openwrt/nf_check.sh | sh -s -- --color off
      changed_when: false
      ignore_errors: true
      register: result

    - name: Clean output
      ansible.builtin.set_fact:
        result: '{{ result.stdout_lines | map("regex_replace", "[\t\"'']", "") | list }}'

    - name: Display output
      ansible.builtin.debug:
        var: result
