- name: Show wireless SSID
  hosts: wireless
  gather_facts: false
  tasks:
    - name: Run wireless_show_ssid.sh
      ansible.builtin.script: ../../openwrt/uci/wireless_show_ssid.sh # run.sh will convert to raw
      changed_when: false
      register: result

    - name: Clean output
      ansible.builtin.set_fact:
        result: '{{ result.stdout_lines | map("regex_replace", "[\t\"'']", "") | list }}'

    - name: Display output
      ansible.builtin.debug:
        var: result

