services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:


# README
# 9443: HTTPS
# 8000: TCP tunnel server port -  Portainer Edge compute features to manage remote Edge agents.
# 9000: HTTP
# after install: docker restart portainer & visit :9000