#!/bin/bash
set -e

# Usage: ./docusaurus.sh <site-name> [target-dir]
# Creates a Docusaurus site in docs-only mode (no blog)

SITE_NAME="${1:-my-docs}"
TARGET_DIR="${2:-.}"
DEST_DIR="$TARGET_DIR/$SITE_NAME"

echo "==> Creating Docusaurus site: $SITE_NAME"
echo "==> Destination: $DEST_DIR"

# Check Node.js version
if ! command -v node &>/dev/null; then
    echo "Error: Node.js is not installed. Please install Node.js >= 18."
    exit 1
fi

NODE_MAJOR=$(node -v | sed 's/v//g' | cut -d. -f1)
if [ "$NODE_MAJOR" -lt 18 ]; then
    echo "Error: Node.js >= 18 is required. Found: $(node -v)"
    exit 1
fi

# Check npm/npx
if ! command -v npx &>/dev/null; then
    echo "Error: npx is not available. Please install npm."
    exit 1
fi

# Remove existing directory if it exists
if [ -d "$DEST_DIR" ]; then
    echo "==> Removing existing directory: $DEST_DIR"
    rm -rf "$DEST_DIR"
fi

# Create Docusaurus classic site
npx create-docusaurus@latest "$DEST_DIR" classic --skip-install --javascript

cd "$DEST_DIR"

# Remove blog files
rm -rf blog

# Remove blog references from docusaurus.config.js
sed -i 's/blog: {/# blog: {/' docusaurus.config.js
sed -i '/showReadingTime/d' docusaurus.config.js
sed -i '/^  \[require\.resolve/d' docusaurus.config.js

# Update docusaurus.config.js for docs-only mode
cat > docusaurus.config.js << 'EOF'
// @ts-check
const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'My Docs',
  tagline: 'Documentation site',
  favicon: 'img/favicon.ico',
  url: 'https://your-docusaurus-site.com',
  baseUrl: '/',
  organizationName: '',
  projectName: '',
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],
  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: 'My Docs',
        logo: {
          alt: 'My Site Logo',
          src: 'img/logo.svg',
        },
        items: [
          {
            href: 'https://github.com',
            label: 'GitHub',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [],
        copyright: `Copyright \u00A9 ${new Date().getFullYear()} My Project.`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
};

module.exports = config;
EOF

# Update sidebars.js for docs-only
cat > sidebars.js << 'EOF'
// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
EOF

# Install dependencies
echo "==> Installing dependencies..."
npm install

# Build to verify
echo "==> Building site..."
npm run build

echo "==> Done! Site created at: $DEST_DIR"
echo "==> To start development server: cd $DEST_DIR && npm start"
