#!/usr/bin/env bash
set -euo pipefail

#===========================================================
# nginx.sh — 将多目录通过 0.0.0.0:8100 暴露为静态文件服务
#
# 配置区：只需修改 PATH_LIST 数组即可增删路径
#  每行一个本地目录，自动映射为同名 URL 前缀
#    /data/scripts  →  http://0.0.0.0:8100/scripts/
#    /data/github   →  http://0.0.0.0:8100/github/
#
# 使用方式:
#   bash nginx.sh          # 启动 / 重载 nginx
#   bash nginx.sh stop     # 停止 nginx
#   bash nginx.sh status   # 查看状态
#===========================================================

PORT=8100
BIND="0.0.0.0"
SERVER_NAME="_"                     # 通配，匹配所有 Host

# ---- 多路径配置（只需修改这个数组） ----
PATH_LIST=(
    /data/scripts
    /data/github
)

# 颜色
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

# ---- 从路径中提取 URL 前缀（如 /data/foo → foo） ----
url_name() {
    basename "$1"
}

# ---- 路径 → conf 文件名（如 /data/scripts → static-data-scripts） ----
conf_base() {
    local name="${1#/}"             # 去掉前导 /
    name="${name//\//-}"            # 剩下的 / 替换为 -
    echo "static-${name}"
}

# 以第一个路径命名统一的配置文件
CONF_FILE="/etc/nginx/conf.d/$(conf_base "${PATH_LIST[0]}").conf"

# ---- 生成 nginx 配置（单个 server 块，多个 location） ----
generate_conf() {
    # 写入 server 块头部
    cat > "$CONF_FILE" <<-NGINX
# Generated by nginx.sh
# Paths: ${PATH_LIST[*]}
server {
    listen       ${BIND}:${PORT};
    server_name  ${SERVER_NAME};

    charset      utf-8;
    autoindex    on;
    autoindex_exact_size  off;
    autoindex_localtime   on;

    # 默认以 raw 方式显示文件内容；仅 .html/.htm 渲染为网页
    default_type  text/plain;
    types {
        text/html  html htm;
    }

NGINX

    # 为每个路径生成两个 location 块：/name/ 和 /name
    for dir in "${PATH_LIST[@]}"; do
        local name
        name="$(url_name "$dir")"
        cat >> "$CONF_FILE" <<-LOC
    # ---- /${name}/ → ${dir}/ ----
    location /${name}/ {
        alias        ${dir}/;
        try_files    \$uri \$uri/ =404;
    }

    location /${name} {
        return 301  /${name}/;
    }

LOC
    done

    # 构建索引页链接列表
    local links=""
    for dir in "${PATH_LIST[@]}"; do
        local name
        name="$(url_name "$dir")"
        links+="<li><a href=\"/${name}/\">/${name}/</a>  →  ${dir}/</li>"
    done

    cat >> "$CONF_FILE" <<-IDX
    # 根路径索引
    location = / {
        default_type  text/html;
        return 200 '<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>File Server :${PORT}</title>
<style>body{font:sans-serif;margin:2em;}li{margin:.5em 0;}a{text-decoration:none;color:#07c;}</style>
</head><body><h2>File Server on :${PORT}</h2>
<ul>
${links}</ul></body></html>';
    }
}
IDX

    echo -e "${GREEN}[OK]${NC} 配置已生成 → ${CONF_FILE}"

    # 清理旧的多路径合并或冗余配置文件
    for old in /etc/nginx/conf.d/multi-path-*.conf \
               /etc/nginx/conf.d/static-*.conf; do
        [[ "$old" == "$CONF_FILE" ]] && continue
        [[ -f "$old" ]] || continue
        rm -f "$old"
        echo -e "${YELLOW}[~]${NC} 已清理旧配置: ${old}"
    done
}

# ---- 安装 nginx ----
install_nginx() {
    if command -v nginx &>/dev/null; then
        echo -e "${YELLOW}[~]${NC} nginx 已安装 ($(nginx -v 2>&1))"
        return 0
    fi

    echo -e "${YELLOW}[~]${NC} 正在安装 nginx ..."
    if command -v apt &>/dev/null; then
        apt update -qq && apt install -y -qq nginx
    elif command -v yum &>/dev/null; then
        yum install -y -q nginx
    elif command -v apk &>/dev/null; then
        apk add --quiet nginx
    else
        echo -e "${RED}[FAIL]${NC} 无法检测包管理器，请手动安装 nginx" >&2
        exit 1
    fi

    # 确保 nginx 主配置引入 conf.d
    if ! grep -q 'include.*conf\.d/\*\.conf' /etc/nginx/nginx.conf 2>/dev/null; then
        mkdir -p /etc/nginx/conf.d
        if ! grep -q 'include.*conf\.d/\*\.conf' /etc/nginx/nginx.conf; then
            sed -i '/^http\s*{/a\    include /etc/nginx/conf.d/*.conf;' /etc/nginx/nginx.conf
        fi
    fi

    echo -e "${GREEN}[OK]${NC} nginx 安装完成"
}

# ---- 确保目录存在 ----
ensure_dirs() {
    for dir in "${PATH_LIST[@]}"; do
        if [[ ! -d "$dir" ]]; then
            echo -e "${YELLOW}[~]${NC} 创建目录: $dir"
            mkdir -p "$dir"
        fi
    done
}

# ---- 构建路径显示字符串 ----
builtin_path_summary() {
    for dir in "${PATH_LIST[@]}"; do
        local name
        name="$(url_name "$dir")"
        echo "    /${name}/  →  ${dir}/"
    done
}

# ---- 测试 & 修复配置 ----
fix_and_test_config() {
    local output rc
    output="$(nginx -t 2>&1)" && rc=$? || true

    if [[ $rc -eq 0 ]]; then
        echo -e "${GREEN}[OK]${NC} nginx -t 通过"
        return 0
    fi

    # 尝试修复 fancyindex 相关错误
    if echo "$output" | grep -qi 'unknown directive.*fancyindex'; then
        echo -e "${YELLOW}[~]${NC} 检测到 fancyindex 模块不可用，自动移除相关指令..."
        sed -i '/^[[:space:]]*fancyindex/d' "$CONF_FILE"
        # 重试
        output="$(nginx -t 2>&1)" && rc=$? || true
    fi

    if [[ $rc -eq 0 ]]; then
        echo -e "${GREEN}[OK]${NC} nginx -t 通过 (已自动修复)"
        return 0
    fi

    echo -e "${RED}[FAIL]${NC} nginx 配置语法错误:" >&2
    echo "$output" >&2
    return 1
}

# ---- 测试 & 重载 ----
start_or_reload() {
    if ! fix_and_test_config; then
        exit 1
    fi

    if nginx -s reload 2>/dev/null; then
        echo -e "${GREEN}[OK]${NC} nginx 已重载"
    else
        echo -e "${YELLOW}[~]${NC} nginx 未运行，正在启动..."
        nginx
        echo -e "${GREEN}[OK]${NC} nginx 已启动"
    fi

    echo ""
    echo -e "  监听: ${GREEN}http://${BIND}:${PORT}${NC}"
    echo "  路径:"
    builtin_path_summary
    echo ""
    echo "  配置文件: ${CONF_FILE}"
}

# ---- 停止 ----
do_stop() {
    if nginx -s stop 2>/dev/null; then
        echo -e "${GREEN}[OK]${NC} nginx 已停止"
    else
        echo -e "${YELLOW}[~]${NC} nginx 似乎未在运行"
    fi
}

# ---- 入口 ----
case "${1:-}" in
    stop)
        do_stop
        exit 0
        ;;
    status)
        if nginx -s quit 2>/dev/null; then :; fi
        if pgrep -x nginx &>/dev/null; then
            echo -e "${GREEN}[OK]${NC} nginx 正在运行"
            echo "  监听端口: $(ss -tlnp 2>/dev/null | grep ":${PORT}" || echo '未检测到')"
        else
            echo -e "${RED}[OFF]${NC} nginx 未运行"
        fi
        exit 0
        ;;
esac

# 主流程：安装 → 生成配置 → 确保目录 → 启动/重载
install_nginx
ensure_dirs
generate_conf
start_or_reload
